# Generated by Django 5.0.14 on 2025-12-03 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("qr_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("has_variants", models.BooleanField(default=False)),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Alert when stock falls below this level",
                        max_digits=12,
                    ),
                ),
                (
                    "expiry_alert_days",
                    models.IntegerField(
                        default=30, help_text="Alert this many days before expiry"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.unit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Color/Size (Red / XL). Optional if product has no variants.",
                        max_length=150,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("sku", models.CharField(max_length=100, unique=True)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in_transit", "In Transit"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("actual_delivery", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="accounts.branch",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="accounts.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity approved for transfer",
                        max_digits=12,
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity actually received",
                        max_digits=12,
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stocktransfer",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        limit_choices_to={"is_warehouse": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_stocks",
                        to="accounts.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        limit_choices_to={"is_warehouse": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_stocks",
                        to="accounts.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "branch"],
                        name="inventory_b_product_5bb5c8_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="inventory_b_expiry__9c523b_idx"
                    ),
                ],
                "unique_together": {("branch", "product", "variant", "batch_number")},
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="inventory_s_is_reso_bca05b_idx",
                    ),
                    models.Index(
                        fields=["product", "branch"],
                        name="inventory_s_product_961618_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase_in", "Purchase (IN)"),
                            ("pos_sale_out", "POS Sale (OUT)"),
                            ("online_order_out", "Online Order (OUT)"),
                            ("transfer_in", "Transfer (IN)"),
                            ("transfer_out", "Transfer (OUT)"),
                            ("return_in", "Return (IN)"),
                            ("damage_out", "Damage (OUT)"),
                            ("adjustment_in", "Manual Adjustment (IN)"),
                            ("adjustment_out", "Manual Adjustment (OUT)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (invoice, order, transfer, etc.)",
                        max_length=100,
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For FIFO cost tracking",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dest_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_dest",
                        to="accounts.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_source",
                        to="accounts.branch",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="inventory_s_created_2ec5f1_idx"
                    ),
                    models.Index(
                        fields=["product", "-created_at"],
                        name="inventory_s_product_cfb4fb_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "-created_at"],
                        name="inventory_s_movemen_a71f62_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["-created_at"], name="inventory_s_created_c8896c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["status", "-created_at"], name="inventory_s_status_e03eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["source_branch", "-created_at"],
                name="inventory_s_source__d1ef96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["destination_branch", "-created_at"],
                name="inventory_s_destina_c3d756_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["transfer_number"], name="inventory_s_transfe_639a89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["product", "branch"], name="inventory_w_product_b5c577_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["expiry_date"], name="inventory_w_expiry__6745df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="warehousestock",
            unique_together={("branch", "product", "variant", "batch_number")},
        ),
    ]
